---

- name: Update apt cache
  become: yes
  apt:
    upgrade: true
    update_cache: yes
    cache_valid_time: 36000

- name: Install required software
  become: yes
  apt:
    state: present
    update_cache: yes
    name: ['python-mysqldb','python-dev', 'libmysqlclient-dev','python3-pip']

- name: Check if pip installed
  command: "pip3 --version"

- name: install dependency
  command: "pip3 install mysql-connector-python"

